networks:
  nrv.net:
    driver: bridge

volumes:
  sql_data_nrv:
    driver: local

services:
  api.nrv:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    env_file: ./env/api.nrv.env
    ports:
      - '35610:80'
    volumes:
      - ./api:/var/php
    working_dir: /var/php
    networks:
      - nrv.net
    depends_on:
      - nrv.db
    command: php -S 0.0.0.0:80 -t /var/php/public
    restart: unless-stopped

  app.nrv:
    image: ubuntu/apache2:latest
    ports:
      - '35611:80'
    volumes:
      - ./app:/var/www/html
    networks:
      - nrv.net
    depends_on:
      - api.nrv
    restart: unless-stopped

  nrv.db:
    image: 'postgres:latest'
    env_file: ./env/nrv.db.env
    ports:
      - '35612:5432'
    networks:
      - nrv.net
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - sql_data_nrv:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: 'adminer:latest'
    ports:
      - '35613:8080'
    networks:
      - nrv.net
    command: 'php -S 0.0.0.0:8080 -t /var/www/html'
    restart: unless-stopped

